repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: autoscaler
    url: https://kubernetes.github.io/autoscaler
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  # Install NGINX first (needed by everything)
  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: ~4.11.0
    values:
      - helm-values/nginx-ingress.yaml
    wait: true
    timeout: 300
    atomic: true

  # Install cert-manager (needed for TLS)
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: ~1.16.0
    values:
      - helm-values/cert-manager.yaml
    set:
      - name: crds.enabled
        value: true
      - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        value: {{ requiredEnv "CERT_MANAGER_ROLE_ARN" }}
    wait: true
    timeout: 300
    atomic: true
    needs:
      - ingress-nginx/ingress-nginx

  # Install external-dns (for Route53)
  - name: external-dns
    namespace: external-dns
    createNamespace: true
    chart: external-dns/external-dns
    version: ~1.15.0
    values:
      - helm-values/external-dns.yaml
    set:
      - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        value: {{ requiredEnv "EXTERNAL_DNS_ROLE_ARN" }}
    wait: true
    timeout: 300
    atomic: true
    needs:
      - ingress-nginx/ingress-nginx

  # Install metrics-server (needed for autoscaling)
  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    version: ~3.12.0
    set:
      - name: args[0]
        value: --kubelet-insecure-tls
    wait: true
    timeout: 180
    atomic: true

  # Install cluster-autoscaler
  - name: cluster-autoscaler
    namespace: kube-system
    chart: autoscaler/cluster-autoscaler
    version: ~9.37.0
    set:
      - name: autoDiscovery.clusterName
        value: {{ requiredEnv "EKS_CLUSTER" }}
      - name: awsRegion
        value: {{ requiredEnv "AWS_REGION" }}
      - name: rbac.serviceAccount.create
        value: true
      - name: rbac.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        value: {{ requiredEnv "CLUSTER_AUTOSCALER_ROLE_ARN" }}
    wait: true
    timeout: 180
    atomic: true
    needs:
      - kube-system/metrics-server

  # Install Prometheus stack
  - name: prometheus
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: ~65.0.0
    wait: true
    timeout: 600
    atomic: true
    needs:
      - cert-manager/cert-manager
      - ingress-nginx/ingress-nginx

  # Install ArgoCD (GitOps controller)
  - name: argocd
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    version: ~7.7.0
    wait: true
    timeout: 600
    atomic: true
    needs:
      - ingress-nginx/ingress-nginx

helmDefaults:
  wait: true
  timeout: 300
  recreatePods: false
  force: false
  atomic: true
  cleanupOnFail: true
  historyMax: 10